### ISSUE TITLE
疫情图无法加载

### ISSUE THREAD

**Issue by MengXin001** [hack-fang/nCov#8]
网页其他内容可以查看，疫情地图无法加载。后台报错如下：
`Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 2463, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 2449, in wsgi_app
    response = self.handle_exception(e)
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1866, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.5/dist-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.5/dist-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/www/wwwroot/api/maps/app.py", line 241, in get_province_data
    provinceName)
  File "/www/wwwroot/api/maps/app.py", line 95, in update_province_all_data
    cities_map_data, province_shortname).dump_options_with_quotes()
  File "/www/wwwroot/api/maps/app.py", line 166, in province_map
    is_map_symbol_show=False
  File "/usr/local/lib/python3.5/dist-packages/pyecharts/charts/map.py", line 18, in add
    self.__add(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/pyecharts/charts/map.py", line 43, in __add
    assert len(attr) == len(value)
AssertionError`

**Comment by hack-fang** [comment]
使用python3.6+版本，`pyecharts` 只支持python3.6+版本，你可以使用虚拟环境运行或者docker运行

**Comment by MengXin001** [comment]
哦哦我是3.5的py，pyecharts我装的低版本

**Comment by hack-fang** [comment]
> 
> 
> 哦哦我是3.5的py，pyecharts我装的低版本

我的开发环境是3.6版本，没有对3.5进行测试，pyecharts新版本也不再支持3.5
